// VFE/src/components/auth/SignInModal.vue
<script lang="ts" setup>
import { ref } from 'vue'
import CModal from '../common/CModal.vue'
import LogoRikai from '../LogoRikai.vue'
import CTextField from '../common/CTextField.vue'
import { useToast } from '../common/toast'
import type { AuthResponse, SignInBody } from '@/types'
import { authEndpoints } from '@/config/endpoints'
import webLocalStorage from '@/utils/webLocalStorage'
import { ACCESS_TOKEN, REFRESH_TOKEN } from '@/config'
import webStorageClient from '@/utils/webStorageClient'
import { api, setAccessToken } from '@/utils/api'
import CLoading from '../common/CLoading.vue'

const isOpen = ref(false)
const { toast } = useToast()
const isLoading = ref<boolean>(false)

function handleSubmin(e: SubmitEvent) {
  e.preventDefault()
  const formData = new FormData(e.currentTarget as HTMLFormElement)

  const body: SignInBody = {
    account: formData.get('account') as string,
    password: formData.get('password') as string,
  }

  isLoading.value = true
  api
    .post<AuthResponse>(authEndpoints.SIGN_IN, body, { skipAuth: true })
    .then((val) => {
      webLocalStorage.set(REFRESH_TOKEN, val.refresh_token)
      webStorageClient.set(ACCESS_TOKEN, val.access_token, {
        expires: new Date(Date.now() + val.expires_in * 1000),
      })
      setAccessToken(val.access_token)
      toast('Đăng nhập thành công!', 'success')
      isOpen.value = false
    })
    .catch(() => {
      toast('Đăng nhập thất bại!', 'warning')
    })
    .finally(() => {
      isLoading.value = false
    })
}
</script>

<template>
  <button
    class="cursor-pointer py-2 px-3.5 bg-gray-300/20 border-separator rounded-3xl hover:bg-gray-300/10 font-medium text-sm"
    @click="isOpen = true"
  >
    Đăng nhập
  </button>

  <CModal :open="isOpen" @close="isOpen = false" size="sm" hide-close-button>
    <template #header>
      <div class="flex flex-col items-center justify-center">
        <LogoRikai :size="75" />
        <h2 class="text-2xl font-bold uppercase">Đăng nhập</h2>
      </div>
    </template>

    <form @submit="handleSubmin">
      <CTextField
        class="my-3"
        type="text"
        label="Tài khoản"
        placeholder="Tên đăng nhập hoặc địa chỉ Email"
        required
        name="account"
        :disabled="isLoading"
      />
      <CTextField
        class="my-3"
        type="password"
        label="Mật khẩu"
        placeholder="Mật khẩu"
        required
        name="password"
        :disabled="isLoading"
      />
      <button
        class="bg-accent text-accent-foreground w-full rounded-full py-2 cursor-pointer mt-5 font-bold"
        type="submit"
        :disabled="isLoading"
      >
        Đăng nhập
      </button>
    </form>
    <CLoading v-if="isLoading" />
  </CModal>
</template>

// FE/components/auth/SignInModal.tsx
"use client";

import {
  Button,
  FieldError,
  Form,
  Input,
  Label,
  Modal,
  TextField,
  toast,
} from "@heroui/react";
import { useCallback, useEffect, useState } from "react";

import { Logo } from "../icons";
import Overlay from "../overlay";

import { SignInBody, useSigninMutation } from "@/store/queries/auth";
import { signin } from "@/store/slices/authSlice";
import { useAppDispatch } from "@/store/hooks";

function SignInForm({
  onClose,
  setLoading,
}: {
  onClose: () => unknown;
  setLoading: (value: boolean) => unknown;
}) {
  const dispatch = useAppDispatch();

  const [signIn, { isLoading }] = useSigninMutation();
  const [errors, setErrors] = useState<any>({});

  useEffect(() => {
    setLoading(isLoading);
  }, [isLoading]);

  const onSubmit = useCallback(
    async (e: any) => {
      e.preventDefault();
      const formData = new FormData(e.currentTarget as HTMLFormElement);

      const body: SignInBody = {
        account: formData.get("account") as string,
        password: formData.get("password") as string,
      };

      try {
        const data = await signIn(body).unwrap();

        toast("Đăng nhập thành công!", { variant: "success" });
        dispatch(
          signin({
            refreshToken: data.refresh_token,
            accessToken: data.access_token,
            expiredInSeconds: data.expires_in,
          }),
        );
        onClose();
      } catch {
        toast("Đăng nhập thất bại! Vui lòng thử lại!", { variant: "warning" });
      }
    },
    [errors, setErrors],
  );

  return (
    <Modal.Body>
      <Form
        className="w-full flex flex-col gap-4 px-5 mt-7"
        validationErrors={errors}
        onSubmit={onSubmit}
      >
        <TextField
          isRequired
          isDisabled={isLoading}
          name="account"
          type="account"
        >
          <Label>Tài khoản</Label>
          <Input
            className="rounded-3xl"
            placeholder="Địa chỉ Email hoặc tên đăng nhập"
          />
          <FieldError />
        </TextField>
        <TextField
          isRequired
          isDisabled={isLoading}
          minLength={8}
          name="password"
          type="password"
        >
          <Label>Mật khẩu</Label>
          <Input className="rounded-3xl" placeholder="Mật khẩu" />
          <FieldError />
        </TextField>

        <Button
          className="w-full uppercase my-1"
          isDisabled={isLoading}
          type="submit"
        >
          Xác nhận
        </Button>
      </Form>
      {isLoading && <Overlay />}
    </Modal.Body>
  );
}

function SignInModal() {
  const [isOpen, setOpen] = useState(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  return (
    <Modal>
      <Button variant="outline" onClick={() => setOpen(!isOpen)}>
        Đăng nhập
      </Button>
      <Modal.Backdrop
        isKeyboardDismissDisabled={!!isLoading}
        isOpen={isOpen}
        shouldCloseOnInteractOutside={() => !isLoading}
        variant="blur"
        onOpenChange={setOpen}
      >
        <Modal.Container size="lg">
          <Modal.Dialog className="sm:max-w-[400px]">
            <Modal.CloseTrigger />
            <Modal.Header className="flex flex-col items-center gap-0">
              <Logo width={100} />
              <Modal.Heading className="text-3xl">ĐĂNG NHẬP</Modal.Heading>
            </Modal.Header>
            <SignInForm
              setLoading={setIsLoading}
              onClose={() => setOpen(false)}
            />
          </Modal.Dialog>
        </Modal.Container>
      </Modal.Backdrop>
    </Modal>
  );
}

export default SignInModal;
